### ISSUE TITLE
rerunning published analysis

### ISSUE THREAD

**Issue by mniederhuber** [snystrom/nystrom-niederhuber_development_2020#1]
Hey bud!

Sorry to bug you with this, but I'm working on my dissertation and getting the talk together. Realizing it might be helpful to regenerate some plots from the paper, but I haven't touched that data in a couple years. 
Wanted to just rerun the published analysis but am trying to avoid having to spend time reprocessing the raw data.

I dug up `E93_GOF_Project_II/` and it looks like all I need to do is copy `ChIP_Data` and `FAIRE_Data` into the repo director and then run the respective `collectData.sh` scripts to make the simlinks.

Is that the right idea?

**Comment by snystrom** [comment]
That _should_ do the right thing.

**Comment by snystrom** [comment]
Let me know if it doesn't. Happy to jump on a call or something to help get it done if you need.

**Comment by mniederhuber** [comment]
yea, so far so good. I had to tweak a couple of things, but i've got the notebook up and running

with your blessing, I'm going to push some changes to the mckay org fork of the repo, and make some copies of the data files on `pierre` to make things more streamlined
I won't make any changes to your `pierre` files, just copy

**Comment by snystrom** [comment]
Yeah go for it. Feel free to submit a PR back to this repo if you like!
